export enum WSRoom {
  INVOICE_SEQUENCE = 'invoice_sequence',
  QUOTATION_SEQUENCE = 'quotation_sequence',
  LOGGER = 'logger',
  EXPENSE_QUOTATION_SEQUENCE = 'EXPENSE_QUOTATION_SEQUENCE',
  EXPENSE_INVOICE_SEQUENCE = 'EXPENSE_INVOICE_SEQUENCE',
}
